# Generated by Django 4.2.23 on 2025-08-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_filme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_filmes/')),
            ],
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.CharField(choices=[('acao', 'Ação'), ('aventura', 'Aventura'), ('misterio', 'Mistério')], max_length=50),
        ),
    ]
