# Generated by Django 4.2.23 on 2025-08-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
        migrations.AddField(
            model_name='filme',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_filmes/'),
        ),
    ]
