# Generated by Django 4.2.23 on 2025-08-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_delete_imagem_filme_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='descricao',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.CharField(choices=[('acao', 'Ação'), ('aventura', 'Aventura'), ('misterio', 'Mistério'), ('ficção', 'Ficção')], max_length=50),
        ),
    ]
